include(FindPackageHandleStandardArgs)

set(SDL_INCLUDE_DIR_0 "SDL_INCLUDE_DIR_0-NOTFOUND" CACHE INTERNAL "dir 0")
set(SDL_INCLUDE_DIR_1 "SDL_INCLUDE_DIR_0-NOTFOUND"  CACHE INTERNAL "dir 1")

find_path(SDL_INCLUDE_DIR_0 SDL.h 
  PATH_SUFFIXES include 
  PATHS "${PROJECT_EXTERNALS_PATH}/SDL-mirror/include" "${PROJECT_EXTERNALS_PATH}/SDL"
)

find_path(SDL_INCLUDE_DIR_1 SDL_config.h
  PATH_SUFFIXES include 
  HINTS "${CMAKE_BINARY_DIR}/externals/SDL-mirror" "${CMAKE_BINARY_DIR}/externals/SDL"
)

set(SDL_INCLUDE_DIR ${SDL_INCLUDE_DIR} ${SDL_INCLUDE_DIR_0} ${SDL_INCLUDE_DIR_1})

find_library( SDL_LIBRARY
        NAMES SDL2
		PATH_SUFFIXES lib
		HINTS "${CMAKE_BINARY_DIR}/externals/SDL-mirror" "${CMAKE_BINARY_DIR}/lib"
		)
		
message("SDL_INCLUDE_DIR: " ${SDL_INCLUDE_DIR})
message("SDL_LIBRARY: " ${SDL_LIBRARY})

FIND_PACKAGE_HANDLE_STANDARD_ARGS(SDL DEFAULT_MSG
                                  SDL_LIBRARY SDL_INCLUDE_DIR)

set(ALL_LIBRARIES ${SDL_LIBRARY} ${ALL_LIBRARIES})